version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ease-chat-app
    ports:
      - "3000:3000"
    volumes:
      # Mount everything except node_modules
      - .:/app
      - /app/node_modules
      # Mount specific folders that should persist
      - .next:/app/.next
    environment:
      - NODE_ENV=development
      # Add any other environment variables your app needs
    command: npm run dev
